### ISSUE TITLE
separate output and code in different branches

### ISSUE THREAD

**Issue by nadinekuo** [EinsteinToolkit/tests#10]
Allows for working on the Python/Bash files without having results being auto-pushed by the ET testing service constantly

This means the workflow should have access to 3 branches now:

- `master` for the Einstein Toolkit C/C++/Fortran code
- `gh-pages` to put results HTML pages in
- `scripts` to get the Python/Bash scripts

This would entail instructing GitHub action to check out the three branches and calling the top-level script (main.yml) with locations for all three checked out branch (or at least 2 since one of them will be the script's location so can be gotten from the $0 bash variable).

See eg [https://github.com/EinsteinToolkit/carpetx-tests/blob/main/.github/workflows/CI.yml](https://github.com/EinsteinToolkit/carpetx-tests/blob/main/.github/workflows/CI.yml) which has:

```
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main
          path: scripts

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
```

to make both the `main` (which we would call `scripts`) and `gh-pages`
 branches available (the Cactus checkout is handled differently in this project since it does not use a single repository but rather calls `GetComponents` directly).
