### ISSUE TITLE
compare to changes made for carpetx-tests and merge "good" changes

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/tests#7]
Roland created a cut down version of the scripts (less spaghetti code as well) in https://github.com/EinsteinToolkit/carpetx-tests and some of the changes should / could be ported back. Eventually we would like to end up with a single set of scripts useful for all projects.

**Comment by nadinekuo** [comment]
You will need to have access to 3 branches:
    - `master` for the Einstein Toolkit C/C++/Fortran code
    - `gh-pages` to put results HTML pages in
    - `py-scripts` to get the Python scripts

You need to check out three branches. See eg [https://github.com/EinsteinToolkit/carpetx-tests/blob/main/.github/workflows/CI.yml](https://github.com/EinsteinToolkit/carpetx-tests/blob/main/.github/workflows/CI.yml) which has:

```
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main
          path: scripts

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
```

to make both the `main` (which we would call `scripts`) and `gh-pages`
 branches available (the Cactus checkout is handled differently in this project since it does not use a single repository but rather calls `GetComponents` directly).
